# Generated by Django 4.2.6 on 2023-10-21 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'verbose_name': 'Tareas', 'verbose_name_plural': 'Tareas'},
        ),
        migrations.AlterField(
            model_name='todo',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
    ]
